title       = "steam"
baseURL     = "https://steam-cli.tamnd.com/"
description = "Browse the Steam game store"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/steam-cli"
